### ISSUE TITLE
Regression in v0.2.0 - Missing UMD build

### ISSUE THREAD

**Issue by sibiraj-s** [millionjs/million#36]
**Describe the bug**

Regression in v0.2.0 - Missing UMD build in the files published to NPM

https://github.com/millionjs/million/blob/6fb1bae08120b4f84f06f170b22a79c79511c654/package.json#L7

**To Reproduce**

See https://unpkg.com/browse/million@0.2.0/dist/

**Comment by aidenybai** [comment]
Thanks for the quick report - on this issue

**Comment by aidenybai** [comment]
Fixed in v0.2.1
